Exclude `swift-autolink-extractor` no-op job for embedded Wasm
This driver job has no effect and is actually prone to failure when Wasm reference types are used:

```
error: autolink-extract command failed with exit code 1 (use -v to see invocation)
.build/wasm32-unknown-none-wasm/release/externref.build/externref.c.o' (invalid data relocation: table)
```